nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['^http://localhost:3000$']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization', 'DNT', 'User-Agent', 'X-Requested-With', 'If-Modified-Since', 'Cache-Control', 'Range']
        expose_headers: ['Content-Length', 'Content-Range']
        max_age: 3600